name: Build Expo App
on:
  push:
    branches:
      - main

jobs:
 
  build-aab:
    name: Build Android App Bundle
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install NPM Packages
        run: npm install

      - name: Expo Android Bundle Build
        run: eas build -p android --profile production
     